services:
  - type: web
    name: my-minecraft-bots
    runtime: node
    repo: https://github.com/yazann21/yzn3mk
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NGROK_AUTHTOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        value: https://yzn3mk.onrender.com/auth/callback